parameters:
    shibboleth.authentication.entry_point.class: Sygefor\Bundle\ApiBundle\Security\ShibbolethAuthenticationEntryPoint

services:
    # override
    security.authentication.entry_point.shibboleth:
      class: %shibboleth.authentication.entry_point.class%
      arguments:
          - @shibboleth
          - @service_container

    # kernel
    sygefor_api.kernel.listener.oauth_public_client:
        class: Sygefor\Bundle\ApiBundle\HttpKernel\EventSubscriber\OauthKernelEventSubscriber
        arguments:
            - @fos_oauth_server.client_manager
            - @fos_oauth_server.server
            - @fos_rest.serializer
        tags:
            - { name: kernel.event_subscriber }

    # serializer
    sygefor_api.serializer.trainee.event_subscriber:
        class: Sygefor\Bundle\ApiBundle\Serializer\EventSubscriber\TraineeEventSubscriber
        tags:
            - { name: jms_serializer.event_subscriber }

    sygefor_api.serializer.training.event_subscriber:
        class: Sygefor\Bundle\ApiBundle\Serializer\EventSubscriber\TrainingEventSubscriber
        tags:
            - { name: jms_serializer.event_subscriber }

    # error parser
    sygefor_api.form_errors.parser:
        class: Sygefor\Bundle\ApiBundle\Service\FormErrorsParser
        calls:
            - [setContainer, ["@service_container"]]

    # shibboleth user provider
    sygefor_api.shibboleth.user_provider:
        class: Sygefor\Bundle\ApiBundle\Security\ShibbolethUserProvider
        arguments:
            - @service_container
            - @sygefor_trainee.user_provider

    # oauth token generator
    sygefor_api.oauth.token_generator:
        class: Sygefor\Bundle\ApiBundle\Security\OAuthTokenGenerator
        arguments:
            - @fos_oauth_server.server
            - @fos_oauth_server.storage
            - @fos_rest.serializer
