sygefor_core:
    resource: "@SygeforCoreBundle/Controller/"
    type:     annotation
    host:     "%back_host%"
    prefix:   /

sygefor_inscription:
    resource: "@SygeforInscriptionBundle/Controller/"
    type:     annotation
    host:     "%back_host%"
    prefix:   /

sygefor_institution:
    resource: "@SygeforInstitutionBundle/Controller/"
    type:     annotation
    host:     "%back_host%"
    prefix:   /

sygefor_trainee:
    resource: "@SygeforTraineeBundle/Controller/"
    type:     annotation
    host:     "%back_host%"
    prefix:   /

sygefor_trainer:
    resource: "@SygeforTrainerBundle/Controller/"
    type:     annotation
    host:     "%back_host%"
    prefix:   /

sygefor_training:
    resource: "@SygeforTrainingBundle/Controller/"
    type:     annotation
    host:     "%back_host%"
    prefix:   /

sygefor_myCompany:
    resource: "@SygeforMyCompanyBundle/Controller/"
    host:     "%back_host%"
    type:     annotation
    prefix:   /

sygefor_activity_report:
    resource: "@SygeforActivityReportBundle/Controller/"
    type:     annotation
    host:     "%back_host%"
    prefix:   /

sygefor_api:
    resource: "@SygeforApiBundle/Controller/"
    type:     annotation
    host:     "%front_host%"
    prefix:   /

sygefor_front:
    resource: "@SygeforFrontBundle/Controller/"
    type:     annotation
    host:     "%front_host%"
    prefix:   /

shibboleth_logout:
    path:   /shibboleth/logout
    host:     "%front_host%"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_oauth_server_token:
    host:     "%front_host%"
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    host:     "%front_host%"
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
