Sygefor\Bundle\CoreBundle\Entity\Organization:
    properties:
      id:
        groups: [Default, api]
      name:
        groups: [Default, api]
      code:
        groups: [Default, api]
      departments:
        groups: [api]
      users:
        exclude: true
      addressType:
        exclude: true
      institutionName:
        groups: [api]
      address:
        groups: [api]
      bp:
        groups: [api]
      zip:
        groups: [api]
      city:
        groups: [api]
      phoneNumber:
        groups: [api]
      faxNumber:
        groups: [api]
      email:
        groups: [api]
      website:
        groups: [api]
      map:
        groups: [api]
    virtual_properties:
      getFullAddress:
        groups: [api]
