parameters:
    sygefor_mycompany.taxonomy.group: "MyCompany"

services:
    sygefor_mycompany.vocabulary_menu_item:
        class:        Sygefor\Bundle\MyCompanyBundle\Entity\Term\MenuItem
        tags:
            - { name: sygefor_core.vocabulary_provider, group: "%sygefor_mycompany.taxonomy.group%" }

    sygefor_mycompany.vocabulary_evaluation_criterion:
        class:        Sygefor\Bundle\MyCompanyBundle\Entity\Term\EvaluationCriterion
        tags:
            - { name: sygefor_core.vocabulary_provider, group: "%sygefor_mycompany.taxonomy.group%" }

        # override term name example
#        sygefor_training.vocabulary_training_theme:
#        class:        Sygefor\Bundle\TrainingBundle\Entity\Training\Term\Theme
#        tags:
#            - { name: sygefor_core.vocabulary_provider, group: "%sygefor_training.taxonomy.group%", label: "Domaine de comp√©tence"}

